[package]
name = "route_parameters"
version = "0.1.0"
authors = ["jochen.deprez <jochen.deprez@student.howest.be>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.6"